{"name": "test_update_task_invalid_id", "status": "passed", "description": "Обновление задачи с несуществующим ID", "steps": [{"name": "Пробуем обновить задачу с фейковым ID", "status": "passed", "start": 1749683109444, "stop": 1749683111137}], "attachments": [{"name": "stdout", "source": "de352e9b-24a6-4428-9c89-28d7a40ff994-attachment.txt", "type": "text/plain"}], "start": 1749683109443, "stop": 1749683111138, "uuid": "3cbb9763-22a9-4c96-9b5d-c236745e701d", "historyId": "719d2b4da1dfef9b6adb89016e3ea409", "testCaseId": "719d2b4da1dfef9b6adb89016e3ea409", "fullName": "tests.api.test_tasks.TestTasks#test_update_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "48776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}