{"name": "test_update_task_invalid_id", "status": "passed", "description": "Обновление задачи с несуществующим ID", "steps": [{"name": "Пробуем обновить задачу с фейковым ID", "status": "passed", "start": 1749683221052, "stop": 1749683222642}], "attachments": [{"name": "stdout", "source": "49b5ebc8-a3f2-4a5e-ac75-8a30953c3ff8-attachment.txt", "type": "text/plain"}], "start": 1749683221051, "stop": 1749683222643, "uuid": "a9874e42-740b-4182-868b-aa81a2d691b1", "historyId": "719d2b4da1dfef9b6adb89016e3ea409", "testCaseId": "719d2b4da1dfef9b6adb89016e3ea409", "fullName": "tests.api.test_tasks.TestTasks#test_update_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "4640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}