{"name": "test_create_task_invalid_id", "status": "passed", "description": "Получение задачи по несуществующему ID", "steps": [{"name": "Пробуем получить задачу с фейковым ID", "status": "passed", "start": 1749921075842, "stop": 1749921077313}], "start": 1749921075842, "stop": 1749921077313, "uuid": "dec830fa-7b51-4035-a8e4-b47e117dd54e", "historyId": "d49665c155321fa39bc7114f9ad62555", "testCaseId": "d49665c155321fa39bc7114f9ad62555", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "8288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}