{"name": "test_create_task_invalid_id", "status": "passed", "description": "Получение задачи по несуществующему ID", "steps": [{"name": "Пробуем получить задачу с фейковым ID", "status": "passed", "start": 1749677906788, "stop": 1749677908513}], "start": 1749677906788, "stop": 1749677908513, "uuid": "fff62fe7-a705-49f1-a29d-63a179583244", "historyId": "d49665c155321fa39bc7114f9ad62555", "testCaseId": "d49665c155321fa39bc7114f9ad62555", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_id", "labels": [{"name": "feature", "value": "Clickup API: Tasks"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "46356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}