{"name": "Тест авторизации: позитивный и негативный логин в одном потоке", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "page = <Page url='https://app.clickup.com/login'>\n\n    @allure.feature(\"UI: Авторизация\")\n    @allure.title(\"Тест авторизации: позитивный и негативный логин в одном потоке\")\n    @allure.description(\"Сначала входим с валидными данными, затем пробуем невалидные и проверяем сообщение об ошибке\")\n    def test_authorization_flow(page):\n        # === Setup ===\n        with allure.step(\"Создаём объект страницы логина\"):\n            login_page = LoginPage(page)\n    \n        # === Test Body ===\n        with allure.step(\"Позитивный логин\"):\n>           login_page.login()\n\ntest_login_page.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\pages\\login_page.py:19: in login\n    self.open()\n..\\..\\pages\\base_page.py:21: in open\n    self.page.goto(full_url)\n..\\..\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py:9024: in goto\n    self._sync(\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002867C711AB0>\ncb = <function Channel.send.<locals>.<lambda> at 0x000002867CB11900>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE             - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n..\\..\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "description": "Сначала входим с валидными данными, затем пробуем невалидные и проверяем сообщение об ошибке", "steps": [{"name": "Создаём объект страницы логина", "status": "passed", "start": 1749839473911, "stop": 1749839473911}, {"name": "Позитивный логин", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\tests\\ui\\test_login_page.py\", line 17, in test_authorization_flow\n    login_page.login()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\login_page.py\", line 19, in login\n    self.open()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 21, in open\n    self.page.goto(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9024, in goto\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Авторизуемся с валидными данными", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\login_page.py\", line 19, in login\n    self.open()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 21, in open\n    self.page.goto(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9024, in goto\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Переход по адресу BASE_URL + endpoint", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\pages\\base_page.py\", line 21, in open\n    self.page.goto(full_url)\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9024, in goto\n    self._sync(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n  File \"C:\\Users\\A\\PycharmProjects\\Project_Сlickup_tests\\clickup_tests\\venv\\lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Формируем полный URL из BASE и endpoint", "status": "passed", "start": 1749839473911, "stop": 1749839473911}], "start": 1749839473911, "stop": 1749839503942}], "start": 1749839473911, "stop": 1749839503943}], "start": 1749839473911, "stop": 1749839503944}], "start": 1749839473911, "stop": 1749839503946, "uuid": "3ef0fe4b-a5ae-49c3-a3e6-6af7b97753c7", "historyId": "a81c7d3605773b89f40d444241d92283", "testCaseId": "a81c7d3605773b89f40d444241d92283", "fullName": "tests.ui.test_login_page#test_authorization_flow", "labels": [{"name": "feature", "value": "UI: Авторизация"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "A1"}, {"name": "thread", "value": "19288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}